name: fun-asr-nano-api
services:
  fun-asr-nano:
    image: ghcr.io/hsiang-han/fun-asr-nano-api:latest
    container_name: fun-asr-nano-api
    build:
      context: ../..
      dockerfile: docker/gpu/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /mnt/user/appdata/fun-asr-nano-api/models:/root/.cache/huggingface
    environment:
      - MODEL_ID=FunAudioLLM/Fun-ASR-Nano-2512
      - DEVICE=cuda:0
      - LANGUAGE=auto
      - ENABLE_VAD=true
      - ENABLE_PUNC=true
      - ENABLE_SPK=false
      - HF_ENDPOINT=https://huggingface.co
      - PORT=8080
    shm_size: "4gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
